version: '3.3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
  express:
    build:
      context: .
      dockerfile: Dockerfile
    command: node build/app.js
    ports:
      - '4200'
  websockets:
    build:
      context: .
      dockerfile: Dockerfile
    command: node build/app.js
    ports:
      - '4420'
